package io.github.jd1378.otphelper

val longtext =
    """
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultrices sagittis convallis. Aliquam mattis arcu sit amet ante finibus, quis commodo ex faucibus. Pellentesque cursus ut leo at tempus. Proin eget molestie justo. Sed facilisis libero eu ex tempor, nec pretium nisl vehicula. Vivamus vitae sagittis felis. Donec quis ligula vel neque mattis aliquam vel lacinia urna. In auctor neque lacus, sit amet luctus nulla pretium nec. Proin venenatis arcu vitae nisi mollis pulvinar. Sed ac dui egestas, varius quam sed, ultrices nulla. Pellentesque interdum ligula maximus, rhoncus velit vel, condimentum sem. Integer id interdum turpis. Praesent eu velit non lacus luctus vulputate ut eu neque.

Suspendisse cursus metus commodo placerat pulvinar. In hac habitasse platea dictumst. Suspendisse blandit in erat sed elementum. Sed blandit commodo tortor rutrum varius. Curabitur ut augue quis lectus scelerisque faucibus. Praesent a urna scelerisque metus auctor molestie vitae id tortor. Proin gravida efficitur felis, a convallis augue iaculis in. Donec nec tincidunt turpis, ut finibus enim. Nam sit amet molestie magna, id congue dui. Praesent ac urna id massa iaculis efficitur sagittis vitae neque. Pellentesque hendrerit, massa quis feugiat ultrices, mi libero blandit odio, semper imperdiet nisl nisi at nulla. Sed porttitor arcu vel laoreet cursus. Proin commodo porttitor porttitor. Curabitur id accumsan nunc. Proin pretium lacinia ante, nec imperdiet magna mollis at. Mauris eget convallis leo, non posuere arcu.

Nunc suscipit sit amet felis in tempus. Fusce luctus auctor lorem quis pharetra. Phasellus scelerisque ultricies ex sed pulvinar. Cras ex arcu, tincidunt non arcu at, bibendum tempor urna. Phasellus pretium quam id elit auctor, id interdum justo ultrices. Etiam egestas viverra nisl quis pellentesque. Proin ut lacus lacus. Cras iaculis congue est eu lobortis. Quisque erat nulla, finibus ac fermentum a, elementum eu quam. Sed scelerisque ipsum vel odio viverra, sed tempor elit pulvinar.

Sed ultricies nulla lacus, eget feugiat lorem scelerisque vitae. In nec neque commodo, tincidunt elit eget, commodo massa. Vestibulum in malesuada tortor. Vestibulum vitae sem lectus. Sed ut purus sit amet velit egestas lacinia et id orci. In hac habitasse platea dictumst. Curabitur tincidunt est efficitur erat elementum dignissim. Nam rutrum convallis mi, et placerat nunc varius ac.

Quisque in justo sed sem condimentum blandit. Curabitur tempor accumsan imperdiet. Fusce augue est, mollis eget magna sit amet, venenatis sollicitudin tellus. Cras aliquam orci sit amet mauris hendrerit malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce congue scelerisque posuere. Ut posuere sapien volutpat, tincidunt nisl vel, porttitor nunc.

Nulla accumsan dapibus nibh, vel porta erat commodo ut. Integer volutpat urna ex, sed imperdiet est venenatis vel. Ut vel fringilla ipsum. Aliquam mi leo, vulputate et nisi ut, mattis dapibus nulla. Cras in risus libero. Mauris finibus consectetur ipsum, ut mollis dui ornare sit amet. Praesent tristique enim ullamcorper dignissim dignissim. Sed vitae vehicula erat, in ullamcorper ipsum. Sed vitae nulla massa. Nam neque turpis, commodo ac odio non, interdum mattis sem. Praesent malesuada nisi vitae augue fringilla facilisis sit amet accumsan lacus. Donec ac rhoncus turpis, ac volutpat dolor. Etiam sit amet auctor diam. Proin sapien diam, euismod bibendum lacus cursus, feugiat semper est.

Fusce ultricies, turpis ac vestibulum molestie, leo lorem condimentum sem, tincidunt laoreet nisi tellus sed mauris. Aenean eu dolor ex. Praesent lobortis mi ut ligula porta, id pharetra nibh suscipit. Morbi congue rutrum pulvinar. Curabitur elementum iaculis lectus, sed feugiat ante imperdiet sit amet. Quisque nisl neque, dapibus et felis et, consectetur pulvinar leo. Curabitur nec magna erat. Nam consequat convallis metus, et ultricies quam aliquet vitae. Duis et diam sapien. Aenean tincidunt pellentesque gravida. Proin purus quam, porta ac ante nec, facilisis facilisis dui. Fusce in nisi placerat, pretium ex id, dictum urna. Nam dictum massa non est consectetur, sed bibendum ex commodo. Aliquam erat volutpat.

Curabitur sed diam quis erat tempus porta nec quis magna. Curabitur non dolor eu libero aliquam molestie. Pellentesque facilisis, orci et blandit iaculis, neque velit ornare tellus, facilisis gravida lectus massa venenatis tortor. Phasellus eleifend ipsum eget arcu fermentum, sed eleifend justo faucibus. Praesent vel sem vel sem suscipit congue id a tortor. Integer euismod dui ac metus lobortis, ac lobortis mi facilisis. Nullam id ligula in lorem condimentum luctus. Etiam et mauris nisl. Nulla facilisi. Praesent non nulla ultricies, malesuada velit a, lacinia sem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras ut ligula in magna feugiat elementum.

Nunc tincidunt venenatis urna, a ultrices odio tincidunt porttitor. Suspendisse potenti. Vestibulum viverra orci at nulla tempor, at eleifend nibh malesuada. Etiam auctor eleifend tortor non hendrerit. Nunc pharetra odio at lorem hendrerit imperdiet. Nam dapibus lectus egestas ligula feugiat pretium. Aenean volutpat nunc ut tellus posuere mattis. Duis at semper justo, eget ornare neque. Vestibulum a tempor est, eu volutpat libero. Maecenas et facilisis sapien, eget tristique leo. Fusce urna tortor, vehicula vitae urna non, fermentum imperdiet velit. Integer id ex at justo vehicula lacinia. Duis vel faucibus velit. Sed accumsan leo orci, id sodales urna suscipit ut. Nam sagittis, elit a ultrices auctor, lacus leo posuere elit, ut fringilla odio nisi vel ipsum.

Duis in posuere nulla. Mauris interdum euismod erat id faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In auctor orci ultrices aliquet cursus. Nullam vel semper neque, vel dignissim urna. In sagittis erat velit, eu molestie lectus porta id. Integer vel diam urna. In vel mi placerat diam mollis euismod. Pellentesque volutpat molestie porta. Nullam fringilla arcu lacus, sed aliquet mauris commodo eu. Vivamus vitae erat justo. Integer vitae auctor massa. Maecenas suscipit dapibus tellus in tincidunt. Etiam eleifend sit amet mi ac iaculis.

OTP 123456
"""
        .trimIndent()
